(#11512) Replace f5 key/cert in one step.
If the certificates and keys are not replaced simultaneously, F5 will
reject the new cert/key because there's a cert/key mismatch:

    Exception: Common::OperationFailed
      primary_error_code   : -14 (0xFFFFFFF2)
      secondary_error_code : 0
      error_string         : Keys do not match

This patch intends to perform key/cert simultanously when updating to
resolve the error above.